# Generated by Django 5.2.1 on 2025-06-22 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Anemometer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(blank=True, related_name='anemometers', to='anemometers.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WindReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anemometer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wind_readings', to='anemometers.anemometer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
