services:
  backend:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    command: sleep infinity
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ..:/src
    user: ${CURRENT_UID}
  
  db:
    image: library/postgres:16-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - dms-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  dms-db:
    driver: local